title: FIT IoT-LAB
description: The Very Large Scale IoT Testbed
url: https://iot-lab.github.io
timezone: Europe/Paris

defaults:
  - scope:
      path: "docs/*"
    values:
      layout: "docs-default"
  - scope:
      path: "docs/boards/*"
    values:
      layout: "docs-board"
  - scope:
      path: "docs/deployment/*"
    values:
      layout: "docs-deployment"
  - scope:
      path: "docs/os/*"
    values:
      layout: "docs-os"
  - scope:
      path: "learn/tutorials/*"
    values:
      layout: "tutorials"
  - scope:
      type: archives
    values:
      layout: "archive"
  - scope:
      path: ""
    values:
      layout: "base"

collections:
    archives:
        output: true

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
