title: FIT IoT-LAB
description: The Very Large Scale IoT Testbed
url: https://www.iot-lab.info
timezone: Europe/Paris

defaults:
  - scope:
      path: "testbed/*"
    values:
      layout: "testbed"
  - scope:
      path: "docs/*"
    values:
      layout: "docs"
  - scope:
      path: "tutorials/*"
    values:
      layout: "tutorials"
  - scope:
      path: ""
    values:
      layout: "default"

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
