title: FIT IoT-LAB
description: The Very Large Scale IoT Testbed
url: https://iot-lab.github.io
timezone: Europe/Paris
permalink: pretty
paginate: 5
paginate_path: "/blog/page:num/"

defaults:
  - scope:
      path: "docs/*"
    values:
      layout: "docs-default"
  - scope:
      path: "docs/boards/*"
    values:
      layout: "docs-board"
  - scope:
      path: "docs/deployment/*"
    values:
      layout: "docs-deployment"
  - scope:
      path: "docs/os/*"
    values:
      layout: "docs-os"
  - scope:
      path: "learn/tutorials/*"
    values:
      layout: "tutorials"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      style: "reduced"
  - scope:
      type: archives
    values:
      layout: "archive"
  - scope:
      path: ""
    values:
      layout: "default"

collections:
    archives:
        output: true

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jemoji
